services:
  - type: web
    name: forge-ide-backend
    runtime: docker
    repo: https://github.com/cheenu-exe/forge-ide.0
    branch: main
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: BACKEND_PORT
        value: $PORT
      - key: EXECUTION_ENGINE
        value: local
      - key: EXECUTION_TIMEOUT_SECONDS
        value: '30'
      - key: EXECUTION_MAX_TIMEOUT_SECONDS
        value: '60'
